In [2]:
import numpy as np

In [3]:
data  = np.random.randn(2,3)
print(data,'\n')
print(data*10)

[[-0.20227003 -0.85955861 -0.50791296]
 [ 0.6891652  -2.2022906  -0.6818001 ]] 

[[ -2.02270033  -8.59558615  -5.07912955]
 [  6.89165195 -22.02290595  -6.81800099]]


In [4]:
print('data shape = ',data.shape)
print('data dtype = ', data.dtype)

data shape =  (2, 3)
data dtype =  float64


In [5]:
data1  = [1,2,3,4,5,6]
print(data1 , type(data1))

arr1 = np.array(data1)
print(arr1 , type(arr1))

[1, 2, 3, 4, 5, 6] <class 'list'>
[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [6]:
data2 = [[1,2,3,4,5],[6,7,8,9,10]]
print(data2)
arr2  = np.array(data2)
print(arr2)
print('Dimension', arr2.ndim)
print('Shape',arr2.shape)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Dimension 2
Shape (2, 5)


In [7]:
print(np.zeros(12),'\n')
print(np.zeros((3,6)),'\n')
print(np.eye(3))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
print(np.arange(11))

[ 0  1  2  3  4  5  6  7  8  9 10]


In [9]:
arr1 = np.array([1,2,3],dtype = np.float64)
arr2 = np.array([1,2,3],dtype = np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [10]:
arr = np.array([1,2,3,4,5])
print(arr , arr.dtype , '\n')

flt = arr.astype(np.float16)
print(flt , flt.dtype)

[1 2 3 4 5] int32 

[1. 2. 3. 4. 5.] float16


In [11]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr.astype(np.int32))

[ 3 -1 -2  0 12 10]


In [12]:
numeric_strings = np.array(['1.25', '-9.6', '42'])
print(numeric_strings , numeric_strings.dtype)
print(numeric_strings.astype(np.float64))
print(numeric_strings.dtype)

['1.25' '-9.6' '42'] <U4
[ 1.25 -9.6  42.  ]
<U4


In [13]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
print(arr ,'\n')
print(arr*arr,'\n')
print(arr+arr,'\n')
print(1/arr,'\n')

[[1. 2. 3.]
 [4. 5. 6.]] 

[[ 1.  4.  9.]
 [16. 25. 36.]] 

[[ 2.  4.  6.]
 [ 8. 10. 12.]] 

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]] 



#  Array indexing n slicing

In [14]:
arr = np.arange(10)
print(arr)
print(arr[5:8])
arr[5:8]=69
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[ 0  1  2  3  4 69 69 69  8  9]


In [15]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])
print(arr2d[0][2])

[7 8 9]
3


In [16]:
print(arr2d[:2])

[[1 2 3]
 [4 5 6]]


# Transposing array n Swapping Axes

In [17]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [19]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [20]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

# Universal Function ufunc

In [21]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
print(np.sqrt(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [23]:
print(np.exp(arr))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [24]:
x = np.random.randn(8)
print(x)

[-0.40834877  0.25632373 -0.23347774  1.2512674   0.7215316  -0.85568361
 -1.42406588 -0.1453766 ]


In [25]:
y = np.random.randn(8)
print(y)

[ 1.22428644 -1.98004512 -2.00816303  0.5602297  -0.2171359  -1.44399825
  1.61112597 -0.51009885]


In [26]:
np.maximum(x,y)

array([ 1.22428644,  0.25632373, -0.23347774,  1.2512674 ,  0.7215316 ,
       -0.85568361,  1.61112597, -0.1453766 ])

# Mathematical n  Statical Methods

In [27]:
arr = np.random.randn(5,4)
print(arr)

[[ 1.30031511 -0.33374906 -0.19534553  1.39835583]
 [ 0.5348012   1.01132757  0.53449753 -0.05840881]
 [-1.92058528  1.46087822 -0.66800582  0.65909455]
 [-0.63879062  0.45980507 -2.07477054 -0.46163596]
 [ 2.57071687  1.82312532  0.22594006  0.59498699]]


In [28]:
print("Mean: ", arr.mean())
print("Mean: ", np.mean(arr))
print("Sum: ", arr.sum())
print("Sum: ", np.sum(arr))

Mean:  0.31112763608221966
Mean:  0.31112763608221966
Sum:  6.222552721644393
Sum:  6.222552721644393


In [30]:
# mean for row
print(arr.mean(axis=1))

[ 0.54239409  0.50555437 -0.11715458 -0.67884801  1.30369231]


In [31]:
# mean for columns
print(arr.mean(axis=0))

[ 0.36929146  0.88427742 -0.43553686  0.42647852]


In [33]:
# sum for row n columns
print(arr.sum(axis=1))
print(arr.sum(axis=0))

[ 2.16957636  2.0222175  -0.46861833 -2.71539205  5.21476924]
[ 1.84645729  4.42138712 -2.1776843   2.13239261]


# Linear Algebra

In [35]:
m1 = np.arange(4).reshape(2,2)
m2 = (np.arange(4)*2).reshape(2,2)
m3 = (np.arange(4)*3).reshape(2,2)

print(m1 ,'\n\n',m2,'\n\n',m3)

[[0 1]
 [2 3]] 

 [[0 2]
 [4 6]] 

 [[0 3]
 [6 9]]


In [36]:
print(np.linalg.multi_dot([m1,m2,m3]))

[[ 36  66]
 [132 234]]


In [41]:
#  3x+y=9 , x+2y=8

a = np.array([[3,1],[1,2]])
b = np.array([9,8])

In [42]:
# Calculating the determinant of square matrix to check the matrix is invertible or not 
print(np.linalg.det(a))

5.000000000000001


In [40]:
# solving linear equation problem using solve fun
print(np.linalg.solve(a,b))

[2. 3.]


In [43]:
#  using inverse function to find inverse of  matrix which exist if determinnat is non zero
print(np.linalg.inv(a))

[[ 0.4 -0.2]
 [-0.2  0.6]]


In [45]:
# using matrix_rank to find the rank of a matrix, indicating the number of linearly independent rows or columns.
print(np.linalg.matrix_rank(a))

2


# array -oriented programming with array

In [48]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])

In [49]:
result = [(x if c else y) for x,y,c in zip(xarr,yarr,cond)]
print(result)

[1.1, 2.2, 1.3, 1.4, 2.5]


In [50]:
result = np.where(cond,xarr,yarr)
print(result)

[1.1 2.2 1.3 1.4 2.5]


In [51]:
arr = np.random.randn(4,4)
print(arr)

[[ 0.27345542 -0.51167344 -0.46109402 -0.45432799]
 [ 0.5611862  -1.79370635  1.45233915  0.39840462]
 [-0.83562936  0.10318935  0.36446703 -0.23961611]
 [-1.07672892 -1.18801026  0.01820394  0.45667133]]


In [52]:
print(arr>0)

[[ True False False False]
 [ True False  True  True]
 [False  True  True False]
 [False False  True  True]]


In [54]:
result = np.where(arr>0,2,-2)
print(result)

[[ 2 -2 -2 -2]
 [ 2 -2  2  2]
 [-2  2  2 -2]
 [-2 -2  2  2]]
